[package]
name = "rp2040-udp-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.3.2"
log = "0.4.14"
simple_logger = "4.3.3"